highsprito/SoloFood

HONBAB/src/main/webapp/WEB-INF/views/main/Board02.jsp
=> Board02.jsp 추가

HONBAB/src/main/java/com/web/honbab/challenge/dto/ChallengeDTO.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeServiceImpl.java, HONBAB/src/main/resources/mappers/challenge/ChallengeMapper.xml
=> level challenge : 수정된 테이블에 맞게 dto, mapper 수정

HONBAB/src/main/java/com/web/honbab/member/controller/MemberController.java, HONBAB/src/main/java/com/web/honbab/member/dto/BizMemberDTO.java, HONBAB/src/main/java/com/web/honbab/member/service/MemberService.java, HONBAB/src/main/java/com/web/honbab/member/service/MemberServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/member/MemberMapper.java, HONBAB/src/main/resources/mappers/member/MemberMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/member/login.jsp
=> 윤하은 사장님 로그인 추가

HONBAB/src/main/java/com/web/honbab/challenge/controller/ChallengeController.java, HONBAB/src/main/java/com/web/honbab/challenge/dto/ChallengeLikeDTO.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeFileServiceImpl.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeLikeService.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeLikeServiceImpl.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeService.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/challenge/ChallengeMapper.java, HONBAB/src/main/resources/mappers/challenge/ChallengeMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeView.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeWriteForm.jsp
좋아요 관련 데이터가 없어 버튼이 바뀌는지 확인은 아직..
=> level challenge : 글 번호 수정, 좋아요 관련 항목 추가

HONBAB/src/main/java/com/web/honbab/admin/controller/OperController.java, HONBAB/src/main/java/com/web/honbab/admin/dto/ADDTO.java, HONBAB/src/main/java/com/web/honbab/admin/dto/AmdinDTO.java, HONBAB/src/main/java/com/web/honbab/admin/dto/NoticeBoardDTO.java, HONBAB/src/main/java/com/web/honbab/admin/dto/NoticeRepDTO.java, HONBAB/src/main/java/com/web/honbab/admin/service/OperService.java, HONBAB/src/main/java/com/web/honbab/admin/service/OperServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/admin/OperMapper.java, HONBAB/src/main/resources/mappers/admin/OperMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/admin/noticeContent.jsp, HONBAB/src/main/webapp/WEB-INF/views/admin/noticeModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/admin/noticeWriteForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/admin/operation.jsp, HONBAB/target/classes/mappers/admin/OperMapper.xml
=> Controller, Service, mybatis, mapper, *jsp, DTO 파일 추가

HONBAB/src/main/java/com/web/honbab/member/controller/MemberController.java, HONBAB/src/main/webapp/WEB-INF/views/member/info.jsp, HONBAB/src/main/webapp/WEB-INF/views/member/login.jsp, HONBAB/src/main/webapp/WEB-INF/views/member/modify.jsp
=> 윤하은 modify 수정진행중

HONBAB/src/main/java/com/web/honbab/admin/controller/OperController.java, HONBAB/src/main/java/com/web/honbab/admin/dto/NoticeBoardDTO.java, HONBAB/src/main/java/com/web/honbab/admin/service/OperService.java, HONBAB/src/main/java/com/web/honbab/admin/service/OperServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/admin/OperMapper.java, HONBAB/src/main/java/com/web/honbab/review/controller/ReviewController.java, HONBAB/src/main/resources/mappers/admin/OperMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/admin/operNoticeContent.jsp, HONBAB/src/main/webapp/WEB-INF/views/admin/operNoticeModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/admin/operNoticeWriteForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/admin/operation.jsp, HONBAB/target/classes/mappers/admin/OperMapper.xml
=> 공지사항게시판 CRUD완료, 다음과제 : 공지댓글

HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeWriteForm.jsp, HONBAB/src/main/webapp/resources/css/challengeWriteForm.css, HONBAB/src/main/webapp/resources/css/main.css
+ challengeWriteForm.jsp : 글 입력 폼 수정
=> main.css : a태그 클릭 시 색 변화 없도록 수정

HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeView.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeWriteForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/main/header.jsp, HONBAB/src/main/webapp/resources/css/allList.css, HONBAB/src/main/webapp/resources/css/header.css, HONBAB/src/main/webapp/resources/css/main.css, HONBAB/src/main/webapp/resources/css/view.css
=> main / header / challenge : 뷰페이지 수정

HONBAB/src/main/java/com/web/honbab/admin/controller/OperController.java, HONBAB/src/main/java/com/web/honbab/admin/service/OperServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/admin/OperMapper.java, HONBAB/src/main/resources/mappers/admin/OperMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/admin/operation.jsp
관리자 : 영업관리 part 
프로토타입 완성
추가 기능 선정중
=> 홍보순서 선택창 보완

HONBAB/src/main/java/com/web/honbab/admin/controller/AdminController.java, HONBAB/src/main/java/com/web/honbab/admin/service/AdminService.java, HONBAB/src/main/java/com/web/honbab/admin/service/AdminServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/admin/AdminMapper.java, HONBAB/src/main/resources/mappers/admin/AdminMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/admin/ADMIndex.jsp, HONBAB/src/main/webapp/WEB-INF/views/admin/adminBan.jsp, HONBAB/src/main/webapp/WEB-INF/views/admin/adminLogin.jsp, HONBAB/target/classes/mappers/admin/AdminMapper.xml
=> 관리자 아이디로 일반회원 삭제 구현

HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeWriteForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findContent.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findWriteForm.jsp, HONBAB/src/main/webapp/resources/css/find/allList.css, HONBAB/src/main/webapp/resources/css/find/view.css
=> find : jsp, css 수정

HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeView.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeWriteForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findContent.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewContent.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewWriteForm.jsp, HONBAB/src/main/webapp/resources/css/challenge/writeForm.css
=> review 폴더 : jsp 전체 수정 css 추가

HONBAB/src/main/java/com/web/honbab/promo/controller/PromoController.java, HONBAB/src/main/webapp/WEB-INF/views/promotion/promoList.jsp
=> 가게홍보에 관리자가 설정한 5개의 광고글 먼저 노출되게 설정함.

HONBAB/src/main/java/com/web/honbab/admin/controller/AdminController.java, HONBAB/src/main/java/com/web/honbab/admin/service/AdminService.java, HONBAB/src/main/java/com/web/honbab/admin/service/AdminServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/admin/AdminMapper.java, HONBAB/src/main/resources/mappers/admin/AdminMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/admin/adminBan.jsp, HONBAB/target/classes/mappers/admin/AdminMapper.xml
=> 관리자 : 일반 회원/파트너 회원 삭제(추방) 완료

HONBAB/src/main/webapp/WEB-INF/views/main/header.jsp, HONBAB/src/main/webapp/resources/css/header.css, HONBAB/src/main/webapp/resources/img/dash-lg.svg
=> <header> : 수정

HONBAB/src/main/java/com/web/honbab/admin/controller/OperController.java, HONBAB/src/main/java/com/web/honbab/admin/service/OperService.java, HONBAB/src/main/java/com/web/honbab/admin/service/OperServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/admin/OperMapper.java, HONBAB/src/main/resources/mappers/admin/OperMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/admin/ADMIndex.jsp, HONBAB/src/main/webapp/WEB-INF/views/member/login.jsp
=> member에 기능이 있는게 깔끔할듯하긴 하지만 충돌이무섭읍니다.. oper에 만듬

HONBAB/src/main/java/com/web/honbab/find/controller/FindController.java, HONBAB/src/main/java/com/web/honbab/find/service/FindServiceImpl.java, HONBAB/src/main/java/com/web/honbab/mybatis/find/FindMapper.java, HONBAB/src/main/resources/mappers/find/FindMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/find/findAllList.jsp
=> 사람찾기 검색기능추가

HONBAB/src/main/webapp/WEB-INF/views/find/bestFind.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/bestReview.jsp
=> best*.jsp 수정함 import하고 경로만 어찌저찌하면 보일거임

HONBAB/src/main/java/com/web/honbab/challenge/controller/ChallengeController.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeService.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeServiceImpl.java, HONBAB/src/main/java/com/web/honbab/find/dto/FindDTO.java, HONBAB/src/main/java/com/web/honbab/main/controller/MainController.java, HONBAB/src/main/java/com/web/honbab/mybatis/challenge/ChallengeMapper.java, HONBAB/src/main/java/com/web/honbab/session/name/MemberSession.java, HONBAB/src/main/resources/mappers/challenge/ChallengeMapper.xml, HONBAB/src/main/resources/mappers/find/FindMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeBest.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findBest.jsp, HONBAB/src/main/webapp/WEB-INF/views/index.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewBest.jsp
=> index에서 bestList 보이면 되는거임

HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeServiceImpl.java, HONBAB/src/main/java/com/web/honbab/find/service/FindFileService.java, HONBAB/src/main/java/com/web/honbab/mybatis/review/ReviewMapper.java, HONBAB/src/main/java/com/web/honbab/review/service/ReviewFileService.java, HONBAB/src/main/java/com/web/honbab/review/service/ReviewServiceImpl.java, HONBAB/src/main/resources/mappers/find/FindMapper.xml, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewModifyForm.jsp
=> 수정하기 기능 손질

HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeBest.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findBest.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findModifyForm.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewBest.jsp, HONBAB/src/main/webapp/resources/css/best.css, HONBAB/src/main/webapp/resources/css/challenge/allList.css, HONBAB/src/main/webapp/resources/css/find/allList.css, HONBAB/src/main/webapp/resources/css/find/writeForm.css, HONBAB/src/main/webapp/resources/css/main.css
challenge allList / allList.css 수정
=> main > best / find > modify : 수정

HONBAB/src/main/java/com/web/honbab/review/controller/ReviewController.java, HONBAB/src/main/java/com/web/honbab/review/service/ReviewService.java, HONBAB/src/main/java/com/web/honbab/review/service/ReviewServiceImpl.java, HONBAB/src/main/webapp/WEB-INF/views/review/reviewContent.jsp
=> 좋아요 색깔변함 로그인안하면 안누른거로 보이게함 (리뷰만 됨)

HONBAB/src/main/java/com/web/honbab/challenge/controller/ChallengeController.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeService.java, HONBAB/src/main/java/com/web/honbab/challenge/service/ChallengeServiceImpl.java, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeAllList.jsp
=> 챌린지 no. 음수나오는거 수정

HONBAB/src/main/java/com/web/honbab/member/controller/IndexController.java, HONBAB/src/main/java/com/web/honbab/member/controller/MemberController.java, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeBest.jsp, HONBAB/src/main/webapp/WEB-INF/views/challenge/challengeView.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findBest.jsp, HONBAB/src/main/webapp/WEB-INF/views/find/findContent.jsp, HONBAB/src/main/webapp/WEB-INF/views/promotion/promoContentView.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewAllList.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewBest.jsp, HONBAB/src/main/webapp/WEB-INF/views/review/reviewContent.jsp, HONBAB/target/classes/mappers/review/ReviewMapper.xml
비회원 글쓰기버튼 보이는 기능 수정
관리자 (글)삭제수정버튼 안보이는 기능 수정
=> login후 best글 안보임, more활성화 안되는 현상 수정

HONBAB/src/main/webapp/resources/css/promo/allList.css, HONBAB/src/main/webapp/resources/css/promo/view.css
=> business 수정
